[package]
authors = ["Molive <moliveofscratch@gmail.com>"]
name = "pico-donk-pc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-donk-core = { path = "../pico-donk-core" }
cpal = "0.13"
